# Change these first
owner: taylor-work # Your GitHub username
repo: 10x-uptime # Your GitHub repository name
user-agent: taylor-work

skipDescriptionUpdate: false
skipTopicsUpdate: true

robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

# Add your sites here
sites:
  - name: BEA.GOV
    url: https://BEA.GOV
  - name: BLDRDOC.GOV
    url: https://BLDRDOC.GOV
  - name: BUYUSA.GOV
    url: https://BUYUSA.GOV
  - name: CENSUS.GOV
    url: https://CENSUS.GOV
  - name: CLIMATE.GOV
    url: https://CLIMATE.GOV
  - name: COMMERCE.GOV
    url: https://COMMERCE.GOV
  - name: DNSOPS.GOV
    url: https://DNSOPS.GOV
  - name: DOC.GOV
    url: https://DOC.GOV
  - name: DROUGHT.GOV
    url: https://DROUGHT.GOV
  - name: EARTHSYSTEMPREDICTION.GOV
    url: https://EARTHSYSTEMPREDICTION.GOV
  - name: EDA.GOV
    url: https://EDA.GOV
  - name: EXPORT.GOV
    url: https://EXPORT.GOV
  - name: FIRSTNET.GOV
    url: https://FIRSTNET.GOV
  - name: FISHWATCH.GOV
    url: https://FISHWATCH.GOV
  - name: GOES-R.GOV
    url: https://GOES-R.GOV


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /10x-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 10x Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 10x - Uptime status page POC.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
